// Lists of content for the Taliesin Generator.

let characterTraits = [
    'You are tough as steel, unbending and indomitable.',
    'You know you are canny, cunning, and clever: all three and no less.',
    'You know what the fates hold in store for you: a life of riches beyond measure.',
    'You are here to right the wrongs of the wicked, and to save the innocent.',
    'Whether in blood or in spirit, you know you were truly born noble.',
    'You\'ve seen worse than this: darkness, terror, and madness.',
    'You believe you are meant for greatness, fame, and to sit upon a high throne.',
    'You know, deep inside, that you are doomed to die, to rot, to be forgotten.',
    'Ever wary and sharp, you are no one\'s fool.',
    'Nothing escapes your watchful gaze and inquisitive mind.',
    'You are willing to do anything it takes to get what you want.',
    'Always in the right place at the right time.',
    'You are filled with dread at what is to come.',
    'You know that you are the one who should be in charge.',
    'You seek redemption: to be forgiven for what you have done or failed to do.',
    'For those evils your hand can avenge, you are prepared to seek justice.',
    'You are learned and worldly, unlike the lot amongst whom you find yourself.',
    'You know how others see you: smooth, charming, and silver-tongued.',
    'You worry that your heart is dark and rotten.',
    'You are filled with lightness, joy, and hope for the future, despite all that has come to pass.',
    'Death makes her home in your heart... none will challenge you without regretting it.',
    'You worry that you are losing your touch.',
    'You fear that you may yet come unhinged.',
    'Your heart is full of kindness and joy, to lift the spirits of those around you.',
    'Who could ever stop you from living a principled life? This much you know: only your own self.',
    'You know that you are far more valuable or skilled than the fools around you.',
    'You know that true beauty shines out from inside you.',
    'The anger inside drives you, indomitable and true, like an arrow to your prey\'s heart.',
    'You are meant for great deeds, to uncover lost secrets, and to bring light into dark places.',
    'Gloom and despair is e\'er your burden, wrapped \'round you like winter\'s cloak.',
    'You meet the challenges of life with stoicism and quiet, steadfast courage.',
    'You are possessed of a quick wit and a disarming smile: always with a ready word on your lips.',
    'Your instincts, intuition, and imagination always lead you to the truth.',
    'Your ambitious spirit drives you: no barrier is insurmountable.',
    'It is only your relentless vigilance that keeps you and your companions alive.',
    'Subtlety and stealth, that is the way to the top of the mountain.',
    'You are not who you seem.',
    'You are a stranger to this place, those who dwell here, and their foreign mores.',
    'So much of your past is shrouded in mystery - lost in the mists of your clouded mind.',
    'Society used to call you a \'lunatic\'. They will learn.',
    'The civilized life was once very foreign to you. In many ways, it still is.',
    'Fortune-telling, omens, and simple divination: everything carries a message for you.',
]

let specialTraits = [
    'Perhaps you are an exiled noble, trying to regain your honour.',
    'Perhaps you are a stranger from a strange land: lost in a storm, your ship wrecked upon these shores, leaving you stranded here for good.',
    'Perhaps you were an assistant to an Imperial researcher, sent here on a quest to collect data for the Imperial Library; if so, you might carry a letter of proof and a leatherskin sketchbook.',
    'Perhaps you are the heir to a major throne, on a quest to prove yourself before you return home to claim it.',
    'Perhaps you are a barbarian prince or princess, far from home, heir to a proud but waning heritage.',
    'Perhaps you are the last of your kind...',
    'They whispered that you were the offspring of a divine being, only half mortal.',
    'It is rumoured that you were the result of a virgin birth.',
    'You also have a rare and special expertise, as an engineer: you know a lot about siege weaponry, fortifications, stone-masonry, tunneling, and map-making.',
    'You once created an artwork, or wrote a book, which has since taken on a life of its own.',
    'You have an excellent relationship with the most notable local religious figure: a priest, priestess, shaman, prophet, or oracle.',
    'You know a famous craftsman, craftswoman, or inventor.',
    'You know a loremaster, who may divulge or research useful information.',
    'You are on good terms with someone powerful: perhaps the local Lord, Lady, Commander, Mayor, or Sheriff.',
    'You are the descendant of a renowned warlord or tyrant, killer of many.',
    'You know a highly-placed member of the Conclave, a mysterious and powerful organization that controls occult knowledge.'
]

let pocketEquipment = [
    'a bedroll',
    'a few pieces of dried meat',
    'a waterskin (full)',
    'a torch, flint, and steel',
    'a backpack'
]

let basicEquipment = [
    // Extras
    'a mask (plain, somber, or decorative)',
    'a warm, thick cloak',
    'a set of iron spikes (6), each as long as your hand',
    // 6
    'a vial of writing ink, quills, and parchment',
    'a whistle',
    'a spyglass',
    'a smoking pipe (and pipeweed)',
    'a small buckler (shield)',
    'a shovel',
    // 5
    'provisions, cured (10 meals)',
    'a vial of perfume',
    'a flask of oil',
    'a mirror and set of lenses',
    'a set of metal files',
    'a magnetic compass',
    // 4
    'a hunter\'s horn',
    'a pair of iron tongs',
    'a jar of grease',
    'a hooded lantern',
    'a pair of leather gloves, thick',
    'a leather coat, thick, with protective padding',
    // 3
    'a fishing net',
    'a pouch of glass marbles (20)',
    'a grappling hook and 20\' of thick rope',
    'a healer\'s kit (bandages, strong liquor, herbs, and poultices)',
    'a pair of high boots, sturdy and well-made',
    'an iron helmet',
    // 2
    'an iron chain (10 ft)',
    'a chisel and a small hammer',
    'climbing gear (50 ft of silk rope, pitons, and spikes)',
    'a pouch holding a peasant\'s life savings (2d6+5 silver coins)',
    'a crowbar',
    'fine clothes, according to your fashion',
    // 1
    'a map of the area',
    'a small bell',
    'a bone flute',
    'a book of lore and legends',
    'a box of chalk',
    'a bucket or cooking pot',
]

let ethericFormulae = [
    'A Demonic Covenant',
    'Shalmanisar\'s Corporeal Diminution',
    'The Apotropaic Barrier',
    'Otiluke\'s Bewitchment',
    'A Chariot of Air',
    'Obsecration',
    'A Subterranean Torrent',
    'Plasmic Manipulation',
    'An Ethereal Boundary',
    'The Final Rite of the Autarch and the Wretch',
]

let flawedFormulae = [
    'The Serpent\'s Kiss (Flawed)',
    'Gaze of Fascination (Unruly)',
    'The Assassin\'s Numen (Flawed)',
    'Soul Transference (Tainted)',
    'Creeping Remnants (Tainted)',
    'The Umbrant Immolation of Maerlish (Unruly)',
]

let basicWeapons = [
    'a shod cudgel',
    'a dagger',
    'a sickle',
    'a scythe',
    'a whip or scourge',
    'a wooden club',
    'a farmer\'s flail',
    'a hatchet',
    'a hunter\'s bow (and a dozen arrows)',
    'a pitchfork',
    'a wooden staff',
    'a wood-splitting axe',
    'a boning knife',
    'a hunting knife',
    'a stiletto',
    'a short spear',
]

let seriousWeapons = {
    'intimidating weapons': [
        'a spiked gauntlet',
        'a morningstar',
        'a battleaxe',
        'a battle pike',
        'a spiked flail',
        'a halberd',
        'a greatsword',
        'a maul',
        'a zweihander',
        'a war club',
        'a length of weighted chain, spiked',
        'a poleaxe',
        'an executioner\'s axe',
    ],
    'others' : [
        'a heavy flail',
        'a flanged mace',
        'a war hammer',
        'a trident',
        'a scimitar',
        'a bastard sword',
        'an arming sword',
        'a falchion',
        'a khopesh',
        'a lance',
        'a mancatcher',
        'a longspear',
        'a cat-gutter (short sword)',
    ]
}

let missileWeapons = [
    'a crossbow',
    'a heavy crossbow',
    'a trio of javelins',
    'a longbow, tall as a man',
    'a recurved bow',
    'a brace of throwing knives (5)',
    'a pair of throwing axes',
    'a sling and stones',
    'a Mongol (horse archer\'s) bow',
    'a composite bow (of horn and sinew)',
]

let elegantWeapons = [
    'a rapier',
    'a cavalry sabre',
    'a long-bladed dueling knife',
    'a slim, jewel-hilted sword',
    'a curved, single-edged sword',
]

let armorTypes = [
    'lamellar armor',
    'banded mail',
    'leather buff coat',
    'brigandine armor',
    'a coat of plates',
    'chain mail',
    'a gambeson or \'padded jack\'',
    'a hauberk (chain shirt)',
    'steel plate mail',
    'scale mail',
    'a steel cuirass',
    'cuir bouilli armor',
    'animal hide armor',
    'great lizard skin armor',
    'bronze hoplite armor',
    'bone armor',
    'bronze banded mail',
    'lacquered steel plate mail',
    'tortoise or insect carapace armor',
    'a bronze breastplate, engraved',
    'a suit of ceramic plates and stitched wood'
]
